[2023-08-23 00:05:07,653] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Nasdaq.obtener_datos_desde_api scheduled__2023-08-22T00:00:00+00:00 [queued]>
[2023-08-23 00:05:07,664] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Nasdaq.obtener_datos_desde_api scheduled__2023-08-22T00:00:00+00:00 [queued]>
[2023-08-23 00:05:07,665] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-08-23 00:05:07,666] {taskinstance.py:1377} INFO - Starting attempt 2 of 6
[2023-08-23 00:05:07,667] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-08-23 00:05:07,682] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): obtener_datos_desde_api> on 2023-08-22 00:00:00+00:00
[2023-08-23 00:05:07,688] {standard_task_runner.py:52} INFO - Started process 940 to run task
[2023-08-23 00:05:07,691] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Nasdaq', 'obtener_datos_desde_api', 'scheduled__2023-08-22T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/Api_Nasdaq.py', '--cfg-path', '/tmp/tmpzepkjgdg', '--error-file', '/tmp/tmpe63flmcw']
[2023-08-23 00:05:07,692] {standard_task_runner.py:80} INFO - Job 11: Subtask obtener_datos_desde_api
[2023-08-23 00:05:07,770] {task_command.py:371} INFO - Running <TaskInstance: Nasdaq.obtener_datos_desde_api scheduled__2023-08-22T00:00:00+00:00 [running]> on host dec66e93643e
[2023-08-23 00:05:07,850] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=marianolopez_coderhouse
AIRFLOW_CTX_DAG_ID=Nasdaq
AIRFLOW_CTX_TASK_ID=obtener_datos_desde_api
AIRFLOW_CTX_EXECUTION_DATE=2023-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-08-22T00:00:00+00:00
[2023-08-23 00:05:12,549] {python.py:173} INFO - Done. Returned value was:             Date    Open    High  ...    Adj. Low  Adj. Close  Adj. Volume
0     2018-03-27  173.68  175.15  ...  166.920000  168.340000   38962839.0
1     2018-03-26  168.07  173.10  ...  166.440000  172.770000   36272617.0
2     2018-03-23  168.39  169.92  ...  164.940000  164.940000   40248954.0
3     2018-03-22  170.00  172.68  ...  168.600000  168.845000   41051076.0
4     2018-03-21  175.04  175.09  ...  171.260000  171.270000   35247358.0
...          ...     ...     ...  ...         ...         ...          ...
9395  1980-12-18   26.63   26.75  ...    0.391536    0.391536   18362400.0
9396  1980-12-17   25.87   26.00  ...    0.380362    0.380362   21610400.0
9397  1980-12-16   25.37   25.37  ...    0.371246    0.371246   26432000.0
9398  1980-12-15   27.38   27.38  ...    0.400652    0.400652   43971200.0
9399  1980-12-12   28.75   28.87  ...    0.422706    0.422706  117258400.0

[9400 rows x 13 columns]
[2023-08-23 00:05:12,579] {xcom.py:586} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-08-23 00:05:12,581] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2412, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 198, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 583, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-08-23 00:05:12,591] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=Nasdaq, task_id=obtener_datos_desde_api, execution_date=20230822T000000, start_date=20230823T000507, end_date=20230823T000512
[2023-08-23 00:05:12,604] {standard_task_runner.py:97} ERROR - Failed to execute job 11 for task obtener_datos_desde_api (Object of type DataFrame is not JSON serializable; 940)
[2023-08-23 00:05:12,617] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-23 00:05:12,668] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
